spring:
  application:
    name: microsrv-eureka-server

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
    #prefer-ip-address: true
    #ip-address: 192.168.1.1

  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000