spring:
  application:
    name: order-service

server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.255.131.162:8000/eureka/,http://10.255.131.163:8000/eureka/,http://10.255.131.164:8000/eureka/

security:
  oauth2:
    resource:
      id: order-service
      #指定用户信息地址
      user-info-uri: https://api.apiboot.cn/auth/user
      prefer-token-info: false


#spring.application.name=order-service
#server.port=8000
#eureka.client.serviceUrl.defaultZone=http://10.255.131.162:8000/eureka/,http://10.255.131.163:8000/eureka/,http://10.255.131.164:8000/eureka/
##开启健康检查（需要 spring-boot-starter-actuator 依赖）
#eureka.client.healthcheck.enabled = true
##租期更新时间间隔（默认30秒）
#eureka.instance.lease-renewal-interval-in-seconds =10
##租期到期时间（默认90秒）
#eureka.instance.lease-expiration-duration-in-seconds =30
##spring.cloud.client.ipAddress=192.168.10.188
#eureka.instance.prefer-ip-address=true
##eureka.instance.instance-id=${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}