logging:
  level:
    org.springframework: DEBUG

spring:
  application:
    name: order-service

server:
  port: 5555

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.255.131.162:8000/eureka/,http://10.255.131.163:8000/eureka/,http://10.255.131.164:8000/eureka/

security:
  oauth2:
    resource:
      #      prefer-token-info: true
      #      user-info-uri: http://localhost:8080/api/v1/users/principal
      #      token-info-uri: http://localhost:8080/oauth/check_token
      jwt:
        # key-uri: http://localhost:8080/oauth/token_key
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm4irSNcR7CSSfXconxL4
          g4M4j34wTWdTv93ocMn4VmdB7rCBU/BlxXtBUf/cgLIgQhQrAPszSZSmxiEXCOkG
          Pr4aQBQuPgmNIR95Dhbzw/ZN0BnecAt3ZfkkDBHv8kH3kR/jYGTdwrxKeDgXGljN
          sTRhbjuASxPG/Z6gU1yRPCsgc2r8NYnztWGcDWqaobqjG3/yzFmusoAboyV7asIp
          o4yk378LmonDNwxnOOTb2Peg5PeelwfOwJPbftK1VOOt18zA0cchw6dHUzq9NlB8
          clps/VdBap9BxU3/0YoFXRIc18nyzrWo2BcY2KQqX//AJC3OAfrfDmo+BGK8E0mp
          8wIDAQAB
          -----END PUBLIC KEY-----


#spring.application.name=order-service
#server.port=8000
#eureka.client.serviceUrl.defaultZone=http://10.255.131.162:8000/eureka/,http://10.255.131.163:8000/eureka/,http://10.255.131.164:8000/eureka/
##开启健康检查（需要 spring-boot-starter-actuator 依赖）
#eureka.client.healthcheck.enabled = true
##租期更新时间间隔（默认30秒）
#eureka.instance.lease-renewal-interval-in-seconds =10
##租期到期时间（默认90秒）
#eureka.instance.lease-expiration-duration-in-seconds =30
##spring.cloud.client.ipAddress=192.168.10.188
#eureka.instance.prefer-ip-address=true
##eureka.instance.instance-id=${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}