server:
  port: 5000

spring:
  application:
    name: microsrv-sleuth-zipkin-server
  #zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
    # baseUrl: http://192.168.99.100:9411/
  sleuth:
    sampler:
      probability: 1.0