logging:
  level:
    org.springframework: INFO #INFO
    org.springframework.security: INFO


spring:
  application:
    name: microsrv-config-client

eureka:
  instance:
    preferIpAddress: true
  #    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://172.23.216.152:8761/eureka/,http://172.23.216.153:8761/eureka/,http://172.23.216.154:8761/eureka/