spring:
  application:
    name: microsrv-eureka-server

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    #ip-address:10.255.131.162

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/