# http://cloud.spring.io/spring-cloud-static/Finchley.RC2/single/spring-cloud.html#_spring_cloud_netflix
spring:
  application:
    name: microsrv-eureka-server

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true #以IP地址注册到服务中心
    #ip-address:10.255.131.162 #强制指定IP地址，默认会使用本机的 IP 地址

  client:
    #表示是否将自己注册到Eureka Server上，默认为true，当前应用为Eureka Server所以无需注册
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
    fetchRegistry: false
    #Eureka Server的访问地址，服务注册和client获取服务注册信息均通过该URL，多个服务注册地址用,隔开
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/