spring:
  application:
    name: microsrv-eureka-server
  profiles:
    active: peer1
#logging:
#  level:
#    com.netflix.eureka: 'off'
#    com.netflix.discovery: 'off'

---
spring:
  profiles: peer1
server:
  port: 8000
eureka:
  instance:
    #hostname: localhost
    #prefer-ip-address: true
    ip-address: 10.255.131.162
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://10.255.131.163:${server.port}/eureka/,http://10.255.131.164:${server.port}/eureka/

---
spring:
  profiles: peer2
server:
  port: 8000
eureka:
  instance:
    #hostname: localhost
    #prefer-ip-address: true
    ip-address: 10.255.131.163
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://10.255.131.162:${server.port}/eureka/,http://10.255.131.164:${server.port}/eureka/

---
spring:
  profiles: peer3
server:
  port: 8000
eureka:
  instance:
    #hostname: localhost
    #prefer-ip-address: true
    ip-address: 10.255.131.164
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://10.255.131.162:${server.port}/eureka/,http://10.255.131.163:${server.port}/eureka/