spring:
  application:
    name: microsrv-oauth2-server
  data:
    mongodb:
      port: 27017
      database: oauth2

server:
  port: 5000

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://10.255.131.162:8000/eureka/,http://10.255.131.163:8000/eureka/,http://10.255.131.164:8000/eureka/
